name: CI Pipeline

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run basic import test
      - name: Test application
        run: |
          python -c "from app.main import app"

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t devops-cicd-demo .